### ISSUE TITLE
Finding the closest zone

### ISSUE THREAD

**Issue by ekohl** [pcorliss/ruby_route_53#42]
Reading https://github.com/pcorliss/ruby_route_53/blob/7be9574b193d528ffd9a1cf250c4e2fb1bf48f32/lib/route53/connection.rb#L63-L71 it would suggest that it almost is able to find the closes zone for a record. I'd expect that if the return was changed to ```return zone_select if zone_select.any?``` it is able to find ```example.com``` when you call ```get_zones('host.sub.example.com')``` but right now it would ```return []```. Is this an oversight, by design or am I missing something?

**Comment by pcorliss** [comment]
@ekohl This is most definitely an oversight on my part. You're correct the intention was to progressively search for zones and the fix is to change `return zone_select` to `return zone_select if zone_select.any?`

If you're feeling up to making the change and adding a test I'd be 👍 on merging it. If not I can probably find some time to take a stab at it this weekend.

Thanks for finding the issue!
